#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"; TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
export CFIP_STATUS_DIR="$TMP" CFIP_RILL_BASE_DIR="$TMP" CFIP_RILL_QUALIFICATION_FILE="$TMP/qualification.json" CFIP_RILL_EVIDENCE_FILE="$TMP/evidence.json" CFIP_RILL_SCHEMA_FILE="$ROOT/package/luci-app-cloudflare-ip/root/usr/share/cf-ip/rill-feature-schema-v2.json" CFIP_RILL_MIN_FEEDBACK_SAMPLES=10 CFIP_RILL_HOLDOUT_INTERVAL=5 CFIP_TARGET_DOMAINS=one.example
source "$ROOT/package/luci-app-cloudflare-ip/root/usr/libexec/cf-ip/common.sh"; source "$ROOT/package/luci-app-cloudflare-ip/root/usr/libexec/cf-ip/rill.sh"
printf '%s\n' '{"candidateOutcome":"success","reward":0.8}' >"$TMP/outcome.json"; printf '%s\n' '{"performed":true,"nativeHoldoutReward":0.7,"actualCandidateReward":0.8,"rewardDelta":0.1,"comparison":"win","failure":false}' >"$TMP/good-holdout.json"; printf '%s\n' '{"decisionId":"seed","effectiveMode":"assisted","nativeOrder":["1.1.1.1"],"authorityActionId":"2.2.2.2","confidenceLevel":"high","confidenceReasons":["qualification_valid"]}' >"$TMP/seed-decision.json"
for _ in $(seq 1 12); do cfip_rill_record_evaluation "$TMP/seed-decision.json" "$TMP/outcome.json" "$TMP/good-holdout.json"; cfip_rill_record_qualification success true true false 0.8 "$TMP/outcome.json"; done; test "$(jq -r .state "$CFIP_RILL_QUALIFICATION_FILE")" = shadow-qualified
for n in $(seq 1 60); do native="10.0.0.$((n%5+1))"; jq -cn --arg id "run-$n" --arg native "$native" '{decisionId:$id,effectiveMode:"assisted",nativeOrder:[$native],authorityActionId:"192.0.2.1",confidenceLevel:"high",confidenceReasons:["qualification_valid"]}' >"$TMP/decision.json"; if cfip_rill_holdout_due "$TMP/decision.json"; then holdout="$TMP/good-holdout.json"; else printf '%s\n' '{"performed":false,"feedbackEligible":false}' >"$TMP/no-holdout.json"; holdout="$TMP/no-holdout.json"; fi; cfip_rill_record_evidence "$TMP/decision.json" "$TMP/outcome.json" "$holdout"; cfip_rill_record_qualification success true true false 0.8 "$TMP/outcome.json"; done
test "$(jq -r .state "$CFIP_RILL_QUALIFICATION_FILE")" = shadow-qualified; test "$(jq -r .evaluationCount "$CFIP_RILL_QUALIFICATION_FILE")" -ge 20; test "$(jq '[.[]|select(.holdoutPerformed==true)]|length' "$CFIP_RILL_EVIDENCE_FILE")" -ge 12
echo '60+ Assisted decisions retain qualification through evaluation holdouts'
