#!/usr/bin/env bash
set -Eeuo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"; TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/bin"; printf '%s\n' '#!/usr/bin/env bash' 'exit 0' >"$TMP/bin/uci"; chmod +x "$TMP/bin/uci"; export PATH="$TMP/bin:$PATH"
export CFIP_LIB_DIR="$ROOT/package/luci-app-cloudflare-ip/root/usr/libexec/cf-ip" CFIP_STATUS_DIR="$TMP/state" CFIP_RUNTIME_DIR="$TMP/runtime" CFIP_LOG_FILE="$TMP/log" CFIP_RILL_ENABLED=true CFIP_RILL_MODE=assisted CFIP_RILL_HOLDOUT_INTERVAL=1 CFIP_RILL_SCHEMA_FILE="$ROOT/package/luci-app-cloudflare-ip/root/usr/share/cf-ip/rill-feature-schema-v2.json" CFIP_RILL_STATE="$TMP/state/state.json" CFIP_RILL_QUALIFICATION_FILE="$TMP/state/q.json" CFIP_RILL_EVIDENCE_FILE="$TMP/state/e.json" CFIP_VALIDATE_CANDIDATE_JSON='{"cf_ip.main.enabled":"1","cf_ip.main.mode":"passwall","cf_ip.main.ip_count":"1","cf_ip.main.ip_type":"ipv4","cf_ip.main.speedtest_protocol":"tcp","cf_ip.main.candidate_budget":"100","cf_ip.main.probe_top_count":"1","cf_ip.main.max_probe_count":"1","cf_ip.main.probe_timeout":"1","cf_ip.main.probe_concurrency":"1","cf_ip.main.probe_batch_size":"1","cf_ip.main.source_policy":"balanced","cf_ip.main.reuse_enabled":"0","cf_ip.main.stop_service":"0","cf_ip.main.cron_interval":"1h","cf_ip.rill.enabled":"1","cf_ip.rill.mode":"assisted","cf_ip.passwall.target_domain":"one.example"}'
source "$ROOT/package/luci-app-cloudflare-ip/root/usr/bin/cf-ip-auto-v2"
ensure_cfst(){ :; }; cfip_prepare_candidate_pool(){ printf '%s\n' '[{"ip":"1.1.1.1","family":"ipv4"}]' >"$1"; printf '%s\n' '1.1.1.1' >"$2"; : >"$3"; }; run_cfst(){ printf '%s\n' '[{"ip":"1.1.1.1","family":"ipv4"}]' >"$CFIP_CANDIDATES_FILE"; }; cfip_rill_probe_priority(){ cp "$1" "$2"; }; cfip_probe_candidates_batched(){ jq 'map(.+{eligible:true,probeSummary:{totalMs:40,ttfbMs:20},lossRate:0,downloadMBps:20})' "$1" >"$2"; }; cfip_rill_update_history(){ :; }; cfip_reuse_try_current(){ return 1; }; cfip_reuse_write_event(){ :; }; cfip_publish_result(){ :; }; write_status(){ :; }; remember_history(){ :; }; cfip_probe_one(){ jq -cn --arg ip "$1" --arg domain "$2" --arg family "$3" '{ip:$ip,domain:$domain,family:$family,success:true,totalMs:40,ttfbMs:20}'; }; cfip_post_apply_probe(){ jq -cn '{validated:true,candidateOutcome:"success",hostOutcome:"success",censored:false,observedIp:"1.1.1.1",decisionActionId:"1.1.1.1",reward:0.8,probes:[{success:true,totalMs:40,ttfbMs:20}]}' >"$4"; }
cfip_txn_prepare(){ CFIP_TXN_DIR="$TMP/txn"; mkdir -p "$CFIP_TXN_DIR"; CFIP_TXN_COMMITTED=false; }; cfip_txn_apply(){ :; }; cfip_txn_commit(){ CFIP_TXN_COMMITTED=true; CFIP_TXN_STATE=COMMITTED; CFIP_TXN_DIR=""; touch "$TMP/committed"; }; cfip_txn_rollback(){ touch "$TMP/rolled-back"; }
cfip_rill_qualified(){ return 0; }; cfip_rill_assisted_ready(){ return 0; }; cfip_rill_rank_shadow(){ printf '%s\n' '{"success":true,"selectedActionId":"2.2.2.2","decisionId":"test","generation":1,"candidates":[{"ip":"2.2.2.2","family":"ipv4","rillRank":1},{"ip":"1.1.1.1","family":"ipv4","rillRank":2}]}' >"$2"; }; select_assisted_candidates(){ printf '%s\n' '[{"ip":"2.2.2.2","family":"ipv4"}]' >"$CFIP_SELECTED_FILE"; }; run_cfst(){ printf '%s\n' '[{"ip":"1.1.1.1","family":"ipv4"},{"ip":"2.2.2.2","family":"ipv4"}]' >"$CFIP_CANDIDATES_FILE"; }; cfip_post_apply_probe(){ jq -cn '{validated:true,candidateOutcome:"success",hostOutcome:"success",censored:false,observedIp:"2.2.2.2",decisionActionId:"2.2.2.2",reward:0.8,probes:[{success:true,totalMs:40,ttfbMs:20}]}' >"$4"; }
cfip_rill_holdout(){ test "${CFIP_TXN_COMMITTED:-false}" = true; touch "$TMP/holdout-called"; jq -cn '{performed:false,reason:"test-noop",feedbackEligible:false}' >"$6"; }
CFIP_SKIP_STARTUP_DELAY=true; run_v2 >/dev/null
test -e "$TMP/committed"; test -e "$TMP/holdout-called"; test ! -e "$TMP/rolled-back"; test -s "$CFIP_RUNTIME_DIR"/run-*/holdout.json
echo 'Production Holdout invocation occurs after transaction commit and cannot rollback committed state'
