'use strict';
'require view';
'require form';
'require uci';
'require rpc';
'require ui';
'require cloudflare-ip/utils as utils';
var callStatus=rpc.declare({object:'cf_ip',method:'status',expect:{'':{}}});
return view.extend({load:function(){return Promise.all([uci.load('cf_ip'),callStatus()]);},render:function(data){utils.loadSharedCSS();var st=(data[1]||{}).intelligence||{},m=new form.Map('cf_ip',_('Rill Intelligence'),_('The generic Rill Runtime is supplied by OpenWrt packaging. Cloudflare IP owns candidate validation, ranking policy, reward and proxy transactions.')),s,o;
 s=m.section(form.TypedSection,'rill',_('Rill Runtime Consumer'));s.anonymous=true;
 o=s.option(form.Flag,'enabled',_('Enable Rill Shadow'));o.default='0';o.rmempty=false;
 o=s.option(form.ListValue,'mode',_('Mode'));o.value('off',_('Off'));o.value('shadow',_('Shadow'));o.value('assisted',_('Assisted (qualification-gated)'));o.default='shadow';
 o=s.option(form.Value,'timeout_ms',_('Runtime Timeout (ms)'));o.datatype='range(100,10000)';o.default='2000';
 o=s.option(form.Value,'runtime',_('Runtime Path'));o.default='/usr/bin/rill-runtime';
 o=s.option(form.Value,'state_file',_('State File'));o.default='/etc/cf_ip/rill-state.json';
 s=m.section(form.TypedSection,'rill',_('Live State'));s.anonymous=true;o=s.option(form.DummyValue,'_state',_('Runtime'));o.cfgvalue=function(){return st.available?(_('Available')+' / '+(st.runtimeVersion||'')):_('Unavailable / Native fallback');};
 return m.render();}});
