'use strict';
'require view';
'require form';
'require uci';
'require rpc';
'require ui';
'require cloudflare-ip/utils as utils';
var callStatus=rpc.declare({object:'cf_ip',method:'status',expect:{'':{}}}),callInstall=rpc.declare({object:'cf_ip',method:'rill-install',expect:{'':{}}}),callRemove=rpc.declare({object:'cf_ip',method:'rill-remove',expect:{'':{}}});
return view.extend({load:function(){return Promise.all([uci.load('cf_ip'),callStatus()]);},render:function(data){utils.loadSharedCSS();var st=(data[1]||{}).intelligence||{},m=new form.Map('cf_ip',_('Rill Intelligence'),_('RillML 1.5.3 is optional and advisory. Native eligibility, transaction health and rollback remain authoritative.')),s,o;
 s=m.section(form.TypedSection,'rill',_('RillML 1.5.3 Shadow Consumer'));s.anonymous=true;
 o=s.option(form.Flag,'enabled',_('Enable Rill Shadow'));o.default='0';o.rmempty=false;
 o=s.option(form.ListValue,'mode',_('Mode'));o.value('off',_('Off'));o.value('shadow',_('Shadow'));o.value('assisted',_('Assisted (qualification-gated)'));o.default='shadow';
 o=s.option(form.Value,'timeout_ms',_('Adapter Timeout (ms)'));o.datatype='range(100,10000)';o.default='2000';
 o=s.option(form.Value,'adapter',_('Adapter Path'));o.default='/usr/libexec/cf-ip/cf-ip-rill';
 o=s.option(form.Value,'state_file',_('State File'));o.default='/etc/cf_ip/rill-state.json';
 o=s.option(form.Button,'_install',_('Install / Verify Adapter'));o.inputtitle=_('Install Rill Adapter');o.inputstyle='apply';o.onclick=function(){return callInstall().then(function(r){ui.addNotification(null,E('p',{},r&&r.success?_('Rill adapter installed and verified.'):_('Rill adapter installation failed.')),r&&r.success?'info':'error');});};
 o=s.option(form.Button,'_remove',_('Remove Adapter'));o.inputtitle=_('Remove Rill Adapter');o.inputstyle='remove';o.onclick=function(){return callRemove().then(function(){window.location.reload();});};
 s=m.section(form.TypedSection,'rill',_('Live State'));s.anonymous=true;o=s.option(form.DummyValue,'_state',_('Adapter'));o.cfgvalue=function(){return st.available?(_('Available')+' / '+(st.rillVersion||'')):_('Unavailable / Native fallback');};
 return m.render();}});
